apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/vfarcic/argocd-app1.git
    targetRevision: HEAD
    helm: # overwrite some values when deploying application
      values: |
        image:
          tag: latest
        ingress:
          host: app1.$INGRESS_HOST.xip.io
      version: v3
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
